const { StyleSheet } = require('@react-pdf/renderer');

const baseStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10.5,
    color: '#1f2937',
    backgroundColor: '#ffffff',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1.5,
    borderBottomColor: '#e5e7eb',
  },
  name: {
    fontSize: 28,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  title: {
    fontSize: 13,
    fontWeight: 600,
    color: '#4b5563',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  contactItem: {
    marginRight: 12,
    paddingRight: 12,
    borderRightWidth: 1,
    borderRightColor: '#d1d5db',
    paddingLeft: 0,
    fontSize: 9.5,
    color: '#6b7280',
  },
  contactItemLast: {
    marginRight: 0,
    paddingRight: 0,
    borderRightWidth: 0,
    borderRightColor: 'transparent',
  },
  section: {
    marginTop: 18,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12.5,
    fontWeight: 700,
    color: '#1e40af',
    marginBottom: 10,
    paddingBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    borderBottomWidth: 1,
    borderBottomColor: '#93c5fd',
  },
  paragraph: {
    fontSize: 10.5,
    lineHeight: 1.6,
    marginBottom: 8,
    color: '#4b5563',
    textAlign: 'justify',
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 6,
    marginLeft: 4,
  },
  bulletPoint: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1e40af',
    marginTop: 6,
    marginRight: 10,
    flexShrink: 0,
  },
  bulletText: {
    fontSize: 10.5,
    lineHeight: 1.6,
    color: '#374151',
    flex: 1,
  },
  jobContainer: {
    marginBottom: 14,
  },
  jobHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  jobTitle: {
    fontSize: 11.5,
    fontWeight: 700,
    color: '#111827',
    flex: 1,
  },
  company: {
    fontSize: 10.5,
    fontWeight: 600,
    color: '#4b5563',
    marginBottom: 6,
  },
  date: {
    fontSize: 9.5,
    color: '#6b7280',
    fontWeight: 600,
    marginLeft: 12,
    flexShrink: 0,
  },
  location: {
    fontSize: 9.5,
    color: '#9ca3af',
    marginBottom: 4,
    fontStyle: 'italic',
  },
  educationContainer: {
    marginBottom: 12,
  },
  degree: {
    fontSize: 11,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 3,
  },
  institution: {
    fontSize: 10.5,
    fontWeight: 600,
    color: '#4b5563',
    marginBottom: 2,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
    marginBottom: 6,
  },
  skillCategory: {
    fontSize: 10,
    fontWeight: 700,
    color: '#1e40af',
    marginBottom: 4,
    marginTop: 8,
  },
  skillTag: {
    backgroundColor: '#eff6ff',
    color: '#1e40af',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 4,
    fontSize: 9.5,
    fontWeight: 600,
    marginRight: 6,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
});

module.exports = { baseStyles };
